FROM httpd:latest
WORKDIR /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/ \
    estilo /usr/local/apache2/htdocs/ \
    fontes /usr/local/apache2/htdocs/ \
    imagens /usr/local/apache2/htdocs/
EXPOSE 80