FROM httpd:latest
WORKDIR /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/
COPY estilo /usr/local/apache2/htdocs/
COPY fontes /usr/local/apache2/htdocs/
COPY imagens /usr/local/apache2/htdocs/
EXPOSE 8051